# Split windows more intuitively:
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Easy reloads of tmux config:
bind r source-file ~/.tmux.conf

set -g mouse on

# Status bar tweaks
set -g status-position top
set -g status-justify absolute-centre
set -g status-style 'fg=yellow bg=black'
set -g status-right '%Y.%m.%d - %H:%M '
set -g status-left ''

# Pane formatting
# set active-inactive window styles
set -g window-style 'fg=#a1a1a1,bg=#27292f'
set -g window-active-style 'fg=#f5f5f5,bg=#212734'

# Tmux Server Message tweaking
set -g display-time 3000
set -g message-line 0
